server:
  port: 80

spring: 
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    static-path-pattern:  /static/**    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/usedshop?characterEncoding=UTF-8
    username: root
    password: root 
    
  mail:       
    host: smtp.gmail.com
    port: 587
    username: seuteut64@gmail.com
    password: ftsatthrguqdjrey
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true    